FROM oven/bun:alpine AS build

WORKDIR /app

COPY . .

RUN bun install
RUN bun run build

FROM oven/bun:alpine AS image

WORKDIR /app

COPY --from=build /app/dist/. ./

EXPOSE 6600

ENTRYPOINT ["./shorty-cluster"]
